pipeline{
  agent any
  stages{
    stage("CI"){
      steps{
        script{
          build()
        }
        static_code_analysis()
      }
    }
    stage("Deployment"){
      steps{
        deploy_to dev
        deploy_to prod
      }
    }
  }
}
